use std::collections::HashMap;

const MAX_NESTED_RECOVERY_BYTES: usize = 64_000;
const MAX_COMPONENT_CALL_BYTES: usize = 128_000;
const MAX_COMPONENT_HELPER_CALLS: usize = 256;

#[derive(Debug, Clone)]
pub struct DecompiledSource {
    pub content: String,
    pub kind: &'static str,
    pub warnings: Vec<String>,
}

#[derive(Debug, Clone)]
struct JsxNode {
    kind: NodeKind,
    attrs: Vec<(String, String)>,
    children: Vec<Child>,
}

#[derive(Debug, Clone)]
enum NodeKind {
    Element(String),
    Text(String),
}

#[derive(Debug, Clone)]
enum Child {
    Node(String),
    Expr(String),
}

pub fn decompile_source(source_name: &str, content: &str) -> Option<DecompiledSource> {
    if !is_opentui_solid_transform(content) {
        return None;
    }

    let mut warnings = Vec::new();
    let stripped = strip_solid_helper_imports(content);
    let recovered_iifes = recover_iifes(&stripped, &mut warnings);
    let recovered = recover_create_components(&recovered_iifes, &mut warnings);
    let mut output = String::new();
    output.push_str("/*\n");
    output.push_str(" * Best-effort JSX recovery generated by bun_binary_extractor.\n");
    output.push_str(" * Source: ");
    output.push_str(source_name);
    output.push('\n');
    output.push_str(" * Provenance: sourcemap.sourcesContent transformed by OpenTUI/Solid universal JSX output.\n");
    output.push_str(
        " * Keep the original sourcesContent file as the authoritative recovered source.\n",
    );
    output.push_str(" */\n\n");
    output.push_str(&recovered);

    Some(DecompiledSource {
        content: output,
        kind: "opentui-solid-jsx",
        warnings,
    })
}

fn is_opentui_solid_transform(content: &str) -> bool {
    content.contains("from \"@opentui/solid\"")
        && (content.contains("_$createElement")
            || content.contains("_$createComponent")
            || content.contains("_$insertNode")
            || content.contains("_$setProp"))
}

fn strip_solid_helper_imports(content: &str) -> String {
    content
        .lines()
        .filter(|line| {
            !(line.contains("from \"@opentui/solid\"")
                && line.contains(" as _$")
                && line.trim_start().starts_with("import "))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn recover_iifes(input: &str, warnings: &mut Vec<String>) -> String {
    let mut out = String::new();
    let mut cursor = 0;
    while let Some(rel) = input[cursor..].find("(() => {") {
        let start = cursor + rel;
        out.push_str(&input[cursor..start]);

        if !should_recover_global_iife(input, start) {
            out.push_str("(() => {");
            cursor = start + "(() => {".len();
            continue;
        }

        let Some((replacement, end)) = transform_iife_at(input, start, warnings) else {
            out.push_str("(() => {");
            cursor = start + "(() => {".len();
            continue;
        };

        out.push_str(&replacement);
        cursor = end;
    }
    out.push_str(&input[cursor..]);
    out
}

fn should_recover_global_iife(input: &str, start: usize) -> bool {
    let before = input[..start].trim_end();
    before.ends_with("return")
        || before.ends_with("=>")
        || before.ends_with('=')
        || before.ends_with('(')
}

fn recover_create_components(input: &str, warnings: &mut Vec<String>) -> String {
    let mut out = String::new();
    let mut cursor = 0;
    while let Some(rel) = input[cursor..].find("_$createComponent") {
        let start = cursor + rel;
        out.push_str(&input[cursor..start]);

        let open = skip_ws(input, start + "_$createComponent".len());
        if input.as_bytes().get(open) != Some(&b'(') {
            out.push_str("_$createComponent");
            cursor = start + "_$createComponent".len();
            continue;
        }
        let Some(close) = find_matching(input, open, b'(', b')') else {
            out.push_str("_$createComponent");
            cursor = start + "_$createComponent".len();
            continue;
        };
        let call = &input[start..=close];
        if should_skip_component_call(call, warnings) {
            out.push_str(call);
        } else if let Some(jsx) = component_to_jsx(call, warnings) {
            out.push_str(&jsx);
        } else {
            out.push_str(call);
        }
        cursor = close + 1;
    }
    out.push_str(&input[cursor..]);
    out
}

fn should_skip_component_call(call: &str, warnings: &mut Vec<String>) -> bool {
    if call.len() > MAX_COMPONENT_CALL_BYTES {
        warnings.push(format!(
            "skipped large Solid component recovery ({} bytes)",
            call.len()
        ));
        return true;
    }

    let helper_calls =
        call.matches("_$createComponent").count() + call.matches("_$createElement").count();
    if helper_calls > MAX_COMPONENT_HELPER_CALLS {
        warnings.push(format!(
            "skipped dense Solid component recovery ({} helper calls)",
            helper_calls
        ));
        return true;
    }

    false
}

fn component_to_jsx_bounded(expr: &str, warnings: &mut Vec<String>) -> Option<String> {
    if should_skip_component_call(expr, warnings) {
        return None;
    }

    component_to_jsx(expr, warnings)
}

fn transform_iife_at(
    input: &str,
    start: usize,
    warnings: &mut Vec<String>,
) -> Option<(String, usize)> {
    let brace = input[start..].find('{')? + start;
    let close_brace = find_matching(input, brace, b'{', b'}')?;
    let mut end = skip_ws(input, close_brace + 1);
    if input.as_bytes().get(end) != Some(&b')') {
        return None;
    }
    end = skip_ws(input, end + 1);
    if input.as_bytes().get(end) != Some(&b'(') {
        return None;
    }
    let close_call = find_matching(input, end, b'(', b')')?;
    let body = &input[brace + 1..close_brace];
    let jsx = parse_iife_body(body, warnings)?;
    Some((jsx, close_call + 1))
}

fn parse_iife_body(body: &str, warnings: &mut Vec<String>) -> Option<String> {
    let statements = split_statements(body);
    let mut nodes: HashMap<String, JsxNode> = HashMap::new();
    let mut root = None;

    for statement in statements {
        let statement = statement.trim();
        if statement.is_empty() {
            continue;
        }
        if statement.starts_with("var ")
            || statement.starts_with("let ")
            || statement.starts_with("const ")
        {
            parse_node_declarations(statement, &mut nodes);
            continue;
        }
        if statement.starts_with("_$insertNode") {
            parse_insert_node(statement, &mut nodes, warnings);
            continue;
        }
        if statement.starts_with("_$insert(") {
            parse_insert(statement, &mut nodes, warnings);
            continue;
        }
        if statement.starts_with("_$setProp") {
            parse_set_prop(statement, &mut nodes, &HashMap::new());
            continue;
        }
        if statement.starts_with("_$effect") {
            parse_effect(statement, &mut nodes);
            continue;
        }
        if statement.starts_with("_$use") {
            parse_use(statement, &mut nodes);
            continue;
        }
        if let Some(value) = statement.strip_prefix("return ") {
            root = Some(value.trim().trim_end_matches(';').trim().to_string());
        }
    }

    let root = root?;
    if nodes.is_empty() {
        return None;
    }
    if root.starts_with('[') {
        return Some(children_expr_to_jsx(&root, warnings));
    }
    if !nodes.contains_key(&root) {
        warnings.push(format!("could not resolve JSX root variable `{root}`"));
        return None;
    }
    Some(render_node(&root, &nodes, 0))
}

fn parse_node_declarations(statement: &str, nodes: &mut HashMap<String, JsxNode>) {
    let statement = statement
        .trim_start_matches("var ")
        .trim_start_matches("let ")
        .trim_start_matches("const ")
        .trim_end_matches(';');
    for decl in split_top_level(statement, b',') {
        let Some((name, expr)) = split_assignment(&decl) else {
            continue;
        };
        let name = name.trim().to_string();
        let expr = expr.trim();
        if let Some(args) = call_args(expr, "_$createElement") {
            if let Some(tag) = args.first().and_then(|arg| string_value(arg)) {
                nodes.insert(
                    name,
                    JsxNode {
                        kind: NodeKind::Element(tag),
                        attrs: Vec::new(),
                        children: Vec::new(),
                    },
                );
            }
            continue;
        }
        if let Some(args) = call_args(expr, "_$createTextNode") {
            if let Some(value) = args.first() {
                nodes.insert(
                    name,
                    JsxNode {
                        kind: NodeKind::Text(value.trim().to_string()),
                        attrs: Vec::new(),
                        children: Vec::new(),
                    },
                );
            }
        }
    }
}

fn parse_insert_node(
    statement: &str,
    nodes: &mut HashMap<String, JsxNode>,
    warnings: &mut Vec<String>,
) {
    let Some(args) = call_args(statement, "_$insertNode") else {
        return;
    };
    if args.len() < 2 {
        return;
    }
    let parent = args[0].trim();
    let child = child_from_expr(args[1].trim(), nodes, warnings);
    if let Some(parent_node) = nodes.get_mut(parent) {
        parent_node.children.push(child);
    }
}

fn parse_insert(statement: &str, nodes: &mut HashMap<String, JsxNode>, warnings: &mut Vec<String>) {
    let Some(args) = call_args(statement, "_$insert") else {
        return;
    };
    if args.len() < 2 {
        return;
    }
    let parent = args[0].trim();
    let child = child_from_expr(args[1].trim(), nodes, warnings);
    if let Some(parent_node) = nodes.get_mut(parent) {
        parent_node.children.push(child);
    }
}

fn parse_set_prop(
    statement: &str,
    nodes: &mut HashMap<String, JsxNode>,
    aliases: &HashMap<String, String>,
) {
    let Some(args) = call_args(statement, "_$setProp") else {
        return;
    };
    apply_set_prop_args(&args, nodes, aliases);
}

fn parse_effect(statement: &str, nodes: &mut HashMap<String, JsxNode>) {
    let aliases = parse_effect_aliases(statement);
    let mut cursor = 0;
    while let Some(rel) = statement[cursor..].find("_$setProp") {
        let start = cursor + rel;
        let Some(args) = call_args(&statement[start..], "_$setProp") else {
            cursor = start + "_$setProp".len();
            continue;
        };
        apply_set_prop_args(&args, nodes, &aliases);
        cursor = start + "_$setProp".len();
    }
}

fn parse_use(statement: &str, nodes: &mut HashMap<String, JsxNode>) {
    let Some(args) = call_args(statement, "_$use") else {
        return;
    };
    if args.len() < 2 {
        return;
    }
    let callback = args[0].trim();
    let element = args[1].trim();
    if let Some(node) = nodes.get_mut(element) {
        set_attr(node, "ref", callback.to_string());
    }
}

fn parse_effect_aliases(statement: &str) -> HashMap<String, String> {
    let mut aliases = HashMap::new();
    let Some(var_pos) = statement.find("var ") else {
        return aliases;
    };
    let after_var = var_pos + "var ".len();
    let Some(end_rel) = statement[after_var..].find(';') else {
        return aliases;
    };
    let decls = &statement[after_var..after_var + end_rel];
    for decl in split_top_level(decls, b',') {
        if let Some((name, expr)) = split_assignment(&decl) {
            aliases.insert(name.trim().to_string(), expr.trim().to_string());
        }
    }
    aliases
}

fn apply_set_prop_args(
    args: &[String],
    nodes: &mut HashMap<String, JsxNode>,
    aliases: &HashMap<String, String>,
) {
    if args.len() < 3 {
        return;
    }
    let node_name = args[0].trim();
    let Some(prop) = string_value(args[1].trim()) else {
        return;
    };
    let value = args[2].trim();
    let value = aliases
        .get(value)
        .cloned()
        .unwrap_or_else(|| value.to_string());
    if let Some(node) = nodes.get_mut(node_name) {
        set_attr(node, &prop, value);
    }
}

fn set_attr(node: &mut JsxNode, prop: &str, value: String) {
    if let Some((_, existing)) = node.attrs.iter_mut().find(|(name, _)| name == prop) {
        *existing = value;
        return;
    }
    node.attrs.push((prop.to_string(), value));
}

fn child_from_expr(
    expr: &str,
    nodes: &HashMap<String, JsxNode>,
    warnings: &mut Vec<String>,
) -> Child {
    let expr = expr.trim();
    if nodes.contains_key(expr) {
        return Child::Node(expr.to_string());
    }
    if let Some(args) = call_args(expr, "_$createTextNode") {
        return Child::Expr(format_child_expr(
            args.first().map(String::as_str).unwrap_or(""),
        ));
    }
    if expr.starts_with("_$createComponent") {
        return Child::Expr(
            component_to_jsx_bounded(expr, warnings).unwrap_or_else(|| format!("{{{expr}}}")),
        );
    }
    if expr.starts_with("() =>") {
        let value = expr.trim_start_matches("() =>").trim();
        return Child::Expr(format!("{{{}}}", expr_to_jsx(value, warnings)));
    }
    if expr.starts_with('[') {
        return Child::Expr(format!("{{{}}}", expr_to_jsx(expr, warnings)));
    }
    Child::Expr(format_child_expr(expr))
}

fn expr_to_jsx(expr: &str, warnings: &mut Vec<String>) -> String {
    let expr = expr.trim().trim_end_matches(';').trim();
    if expr.starts_with("(() => {") {
        if let Some((jsx, end)) = transform_iife_at(expr, 0, warnings) {
            if end == expr.len() {
                return jsx;
            }
        }
    }
    if expr.starts_with("_$createComponent") {
        return component_to_jsx_bounded(expr, warnings).unwrap_or_else(|| expr.to_string());
    }
    if expr.starts_with('[') {
        return render_array_expr(expr, warnings);
    }
    expr.to_string()
}

fn render_array_expr(expr: &str, warnings: &mut Vec<String>) -> String {
    if expr.len() > MAX_NESTED_RECOVERY_BYTES {
        warnings.push(format!(
            "skipped nested JSX recovery for large expression ({} bytes)",
            expr.len()
        ));
        return expr.to_string();
    }

    let Some(body) = strip_wrapping(expr, b'[', b']') else {
        return expr.to_string();
    };
    let rendered = split_top_level(body, b',')
        .into_iter()
        .map(|part| expr_to_jsx(&part, warnings))
        .collect::<Vec<_>>();
    format!("[{}]", rendered.join(", "))
}

fn children_expr_to_jsx(expr: &str, warnings: &mut Vec<String>) -> String {
    let expr = expr.trim().trim_end_matches(';').trim();
    if expr.starts_with('[') {
        return render_children_array(expr, warnings);
    }
    if let Some(unquoted) = string_value(expr) {
        return escape_jsx_text(&unquoted);
    }

    let rendered = expr_to_jsx(expr, warnings);
    if rendered.starts_with('<') || rendered.starts_with('{') {
        rendered
    } else {
        format!("{{{rendered}}}")
    }
}

fn render_children_array(expr: &str, warnings: &mut Vec<String>) -> String {
    if expr.len() > MAX_NESTED_RECOVERY_BYTES {
        warnings.push(format!(
            "skipped nested JSX children recovery for large array expression ({} bytes)",
            expr.len()
        ));
        return format!("{{{expr}}}");
    }

    let Some(body) = strip_wrapping(expr, b'[', b']') else {
        return format!("{{{expr}}}");
    };
    split_top_level(body, b',')
        .into_iter()
        .filter_map(|part| {
            let part = part.trim();
            (!part.is_empty()).then(|| children_expr_to_jsx(part, warnings))
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn component_to_jsx(expr: &str, warnings: &mut Vec<String>) -> Option<String> {
    let args = call_args(expr, "_$createComponent")?;
    if args.is_empty() {
        return None;
    }
    let component = args[0].trim();
    let props = args.get(1).map(|arg| arg.trim()).unwrap_or("{}");
    let (attrs, children) = parse_component_props(props, warnings);
    let attrs = render_attrs(&attrs);
    if let Some(children) = children {
        Some(format!(
            "<{component}{attrs}>{children}</{component}>",
            component = component,
            attrs = attrs,
            children = children
        ))
    } else {
        Some(format!("<{component}{attrs} />"))
    }
}

fn parse_component_props(
    props: &str,
    warnings: &mut Vec<String>,
) -> (Vec<(String, String)>, Option<String>) {
    let mut attrs = Vec::new();
    let mut children = None;
    let Some(body) = strip_wrapping(props, b'{', b'}') else {
        return (attrs, children);
    };
    for field in split_top_level(body, b',') {
        let field = field.trim();
        if field.is_empty() {
            continue;
        }
        if let Some((name, value)) = parse_getter_field(field, warnings) {
            if name == "children" {
                children = Some(value);
            } else {
                attrs.push((name, value));
            }
            continue;
        }
        let Some((name, value)) = split_object_field(field) else {
            continue;
        };
        let name = name.trim().to_string();
        let value = value.trim();
        if name == "children" {
            children = Some(component_children_value(value, warnings));
        } else {
            attrs.push((name, expr_to_jsx(value, warnings)));
        }
    }
    (attrs, children)
}

fn parse_getter_field(field: &str, warnings: &mut Vec<String>) -> Option<(String, String)> {
    let field = field.trim();
    let rest = field.strip_prefix("get ")?;
    let name_end = rest.find("()")?;
    let name = rest[..name_end].trim().to_string();
    let brace_start = field.find('{')?;
    let brace_end = find_matching(field, brace_start, b'{', b'}')?;
    let body = &field[brace_start + 1..brace_end];
    let return_expr = extract_return_expr(body);
    if matches!(name.as_str(), "children" | "fallback") {
        if let Some(expr) = return_expr.as_deref() {
            let expr = expr.trim();
            if should_recover_children_return_directly(expr) {
                return Some((name, children_expr_to_jsx(expr, warnings)));
            }
        }
    }
    if matches!(name.as_str(), "children" | "fallback") && body.contains("_$createElement") {
        let mut local_warnings = Vec::new();
        if let Some(jsx) = parse_iife_body(body, &mut local_warnings) {
            warnings.extend(local_warnings);
            return Some((name, jsx));
        }
    }
    let expr = return_expr.unwrap_or_else(|| body.trim().to_string());
    if matches!(name.as_str(), "children" | "fallback") {
        return Some((name, children_expr_to_jsx(&expr, warnings)));
    }
    Some((name, expr_to_jsx(&expr, warnings)))
}

fn should_recover_children_return_directly(expr: &str) -> bool {
    expr.starts_with('[')
        || expr.starts_with("_$createComponent")
        || expr.starts_with("(() => {")
        || string_value(expr).is_some()
}

fn component_children_value(value: &str, warnings: &mut Vec<String>) -> String {
    if let Some((param, body)) = split_arrow(value) {
        return format!(
            "{{{} => {}}}",
            param.trim(),
            expr_to_jsx(body.trim(), warnings)
        );
    }
    children_expr_to_jsx(value, warnings)
}

fn split_arrow(value: &str) -> Option<(&str, &str)> {
    let idx = find_top_level_token(value, "=>")?;
    Some((&value[..idx], &value[idx + 2..]))
}

fn extract_return_expr(body: &str) -> Option<String> {
    for statement in split_statements(body) {
        let statement = statement.trim();
        if let Some(expr) = statement.strip_prefix("return ") {
            return Some(expr.trim().trim_end_matches(';').trim().to_string());
        }
    }
    None
}

fn render_node(name: &str, nodes: &HashMap<String, JsxNode>, indent: usize) -> String {
    let Some(node) = nodes.get(name) else {
        return format!("{{{name}}}");
    };
    match &node.kind {
        NodeKind::Text(value) => format_child_expr(value),
        NodeKind::Element(tag) => {
            let attrs = render_attrs(&node.attrs);
            if node.children.is_empty() {
                return format!("<{tag}{attrs} />");
            }

            let pad = " ".repeat(indent);
            let child_pad = " ".repeat(indent + 2);
            let mut out = format!("<{tag}{attrs}>");
            let multi = node.children.len() > 1
                || node
                    .children
                    .iter()
                    .any(|child| matches!(child, Child::Node(_)));
            if multi {
                out.push('\n');
            }
            for child in &node.children {
                let rendered = match child {
                    Child::Node(child_name) => render_node(child_name, nodes, indent + 2),
                    Child::Expr(expr) => expr.clone(),
                };
                if multi {
                    out.push_str(&child_pad);
                    out.push_str(&indent_multiline(&rendered, indent + 2));
                    out.push('\n');
                } else {
                    out.push_str(&rendered);
                }
            }
            if multi {
                out.push_str(&pad);
            }
            out.push_str(&format!("</{tag}>"));
            out
        }
    }
}

fn render_attrs(attrs: &[(String, String)]) -> String {
    if attrs.is_empty() {
        return String::new();
    }
    let mut out = String::new();
    for (name, value) in attrs {
        out.push(' ');
        out.push_str(name);
        if value == "true" {
            continue;
        }
        out.push('=');
        out.push_str(&format_attr_value(value));
    }
    out
}

fn format_attr_value(value: &str) -> String {
    if let Some(unquoted) = string_value(value) {
        if is_simple_attr_string(&unquoted) {
            return format!("\"{}\"", unquoted.replace('"', "&quot;"));
        }
    }
    format!("{{{}}}", value.trim())
}

fn format_child_expr(value: &str) -> String {
    let value = value.trim();
    if let Some(unquoted) = string_value(value) {
        if !unquoted.contains('{') && !unquoted.contains('}') && !unquoted.contains('\n') {
            return escape_jsx_text(&unquoted);
        }
    }
    format!("{{{value}}}")
}

fn indent_multiline(value: &str, indent: usize) -> String {
    let pad = " ".repeat(indent);
    value
        .lines()
        .enumerate()
        .map(|(idx, line)| {
            if idx == 0 {
                line.to_string()
            } else {
                format!("{pad}{line}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn is_simple_attr_string(value: &str) -> bool {
    value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | ' ' | ':' | '/' | '.'))
}

fn escape_jsx_text(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

fn split_statements(input: &str) -> Vec<String> {
    split_top_level(input, b';')
}

fn split_top_level(input: &str, delimiter: u8) -> Vec<String> {
    let mut parts = Vec::new();
    let mut start = 0;
    let mut depth_paren = 0usize;
    let mut depth_brace = 0usize;
    let mut depth_bracket = 0usize;
    let mut state = ScanState::default();
    let bytes = input.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        state.advance(input, &mut i);
        if state.in_literal_or_comment() {
            i += 1;
            continue;
        }
        match bytes[i] {
            b'(' => depth_paren += 1,
            b')' => depth_paren = depth_paren.saturating_sub(1),
            b'{' => depth_brace += 1,
            b'}' => depth_brace = depth_brace.saturating_sub(1),
            b'[' => depth_bracket += 1,
            b']' => depth_bracket = depth_bracket.saturating_sub(1),
            b if b == delimiter && depth_paren == 0 && depth_brace == 0 && depth_bracket == 0 => {
                parts.push(input[start..i].to_string());
                start = i + 1;
            }
            _ => {}
        }
        i += 1;
    }
    if start < input.len() {
        parts.push(input[start..].to_string());
    }
    parts
}

fn split_assignment(input: &str) -> Option<(&str, &str)> {
    let idx = find_top_level_byte(input, b'=')?;
    Some((&input[..idx], &input[idx + 1..]))
}

fn split_object_field(input: &str) -> Option<(&str, &str)> {
    let idx = find_top_level_byte(input, b':')?;
    Some((&input[..idx], &input[idx + 1..]))
}

fn find_top_level_byte(input: &str, needle: u8) -> Option<usize> {
    let mut depth_paren = 0usize;
    let mut depth_brace = 0usize;
    let mut depth_bracket = 0usize;
    let mut state = ScanState::default();
    let bytes = input.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        state.advance(input, &mut i);
        if state.in_literal_or_comment() {
            i += 1;
            continue;
        }
        match bytes[i] {
            b'(' => depth_paren += 1,
            b')' => depth_paren = depth_paren.saturating_sub(1),
            b'{' => depth_brace += 1,
            b'}' => depth_brace = depth_brace.saturating_sub(1),
            b'[' => depth_bracket += 1,
            b']' => depth_bracket = depth_bracket.saturating_sub(1),
            b if b == needle && depth_paren == 0 && depth_brace == 0 && depth_bracket == 0 => {
                return Some(i);
            }
            _ => {}
        }
        i += 1;
    }
    None
}

fn find_top_level_token(input: &str, token: &str) -> Option<usize> {
    let mut depth_paren = 0usize;
    let mut depth_brace = 0usize;
    let mut depth_bracket = 0usize;
    let mut state = ScanState::default();
    let bytes = input.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        state.advance(input, &mut i);
        if state.in_literal_or_comment() {
            i += 1;
            continue;
        }
        match bytes[i] {
            b'(' => depth_paren += 1,
            b')' => depth_paren = depth_paren.saturating_sub(1),
            b'{' => depth_brace += 1,
            b'}' => depth_brace = depth_brace.saturating_sub(1),
            b'[' => depth_bracket += 1,
            b']' => depth_bracket = depth_bracket.saturating_sub(1),
            _ => {}
        }
        if depth_paren == 0
            && depth_brace == 0
            && depth_bracket == 0
            && input[i..].starts_with(token)
        {
            return Some(i);
        }
        i += 1;
    }
    None
}

fn call_args(input: &str, function: &str) -> Option<Vec<String>> {
    let input = input.trim();
    if !input.starts_with(function) {
        return None;
    }
    let open = skip_ws(input, function.len());
    if input.as_bytes().get(open) != Some(&b'(') {
        return None;
    }
    let close = find_matching(input, open, b'(', b')')?;
    Some(split_top_level(&input[open + 1..close], b','))
}

fn strip_wrapping(input: &str, open: u8, close: u8) -> Option<&str> {
    let input = input.trim();
    if input.as_bytes().first() != Some(&open) {
        return None;
    }
    let end = find_matching(input, 0, open, close)?;
    if skip_ws(input, end + 1) != input.len() {
        return None;
    }
    Some(&input[1..end])
}

fn string_value(input: &str) -> Option<String> {
    let input = input.trim();
    let quote = *input.as_bytes().first()?;
    if !matches!(quote, b'"' | b'\'' | b'`') {
        return None;
    }
    if input.as_bytes().last() != Some(&quote) {
        return None;
    }
    Some(input[1..input.len() - 1].to_string())
}

fn skip_ws(input: &str, mut cursor: usize) -> usize {
    while cursor < input.len() && input.as_bytes()[cursor].is_ascii_whitespace() {
        cursor += 1;
    }
    cursor
}

fn find_matching(input: &str, open_pos: usize, open: u8, close: u8) -> Option<usize> {
    let bytes = input.as_bytes();
    if bytes.get(open_pos) != Some(&open) {
        return None;
    }
    let mut depth = 0usize;
    let mut state = ScanState::default();
    let mut i = open_pos;
    while i < bytes.len() {
        state.advance(input, &mut i);
        if state.in_literal_or_comment() {
            i += 1;
            continue;
        }
        if bytes[i] == open {
            depth += 1;
        } else if bytes[i] == close {
            depth = depth.saturating_sub(1);
            if depth == 0 {
                return Some(i);
            }
        }
        i += 1;
    }
    None
}

#[derive(Default)]
struct ScanState {
    quote: Option<u8>,
    escaped: bool,
    line_comment: bool,
    block_comment: bool,
}

impl ScanState {
    fn in_literal_or_comment(&self) -> bool {
        self.quote.is_some() || self.line_comment || self.block_comment
    }

    fn advance(&mut self, input: &str, cursor: &mut usize) {
        let bytes = input.as_bytes();
        let i = *cursor;
        if i >= bytes.len() {
            return;
        }

        if self.line_comment {
            if bytes[i] == b'\n' {
                self.line_comment = false;
            }
            return;
        }

        if self.block_comment {
            if bytes[i] == b'*' && bytes.get(i + 1) == Some(&b'/') {
                self.block_comment = false;
                *cursor += 1;
            }
            return;
        }

        if let Some(quote) = self.quote {
            if self.escaped {
                self.escaped = false;
                return;
            }
            if bytes[i] == b'\\' {
                self.escaped = true;
                return;
            }
            if bytes[i] == quote {
                self.quote = None;
            }
            return;
        }

        if bytes[i] == b'/' && bytes.get(i + 1) == Some(&b'/') {
            self.line_comment = true;
            *cursor += 1;
            return;
        }
        if bytes[i] == b'/' && bytes.get(i + 1) == Some(&b'*') {
            self.block_comment = true;
            *cursor += 1;
            return;
        }
        if matches!(bytes[i], b'\'' | b'"' | b'`') {
            self.quote = Some(bytes[i]);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recovers_simple_opentui_solid_iife() {
        let input = r#"import { createElement as _$createElement } from "@opentui/solid";
import { insertNode as _$insertNode } from "@opentui/solid";
import { setProp as _$setProp } from "@opentui/solid";
export function Home() {
  return (() => {
    var _el$ = _$createElement("box"),
      _el$2 = _$createElement("text");
    _$insertNode(_el$, _el$2);
    _$setProp(_el$, "flexGrow", 1);
    _$insertNode(_el$2, _$createTextNode(`hello`));
    return _el$;
  })();
}
"#;
        let out = decompile_source("home.tsx", input).unwrap().content;
        assert!(out.contains("<box flexGrow={1}>"));
        assert!(out.contains("<text>hello</text>"));
        assert!(!out.contains(" as _$createElement"));
    }

    #[test]
    fn recovers_component_children() {
        let input = r#"import { createComponent as _$createComponent } from "@opentui/solid";
import { createElement as _$createElement } from "@opentui/solid";
import { insert as _$insert } from "@opentui/solid";
export function Home() {
  return (() => {
    var _el$ = _$createElement("box");
    _$insert(_el$, _$createComponent(Show, {
      get when() {
        return ready();
      },
      get children() {
        var _el$2 = _$createElement("text");
        return _el$2;
      }
    }), null);
    return _el$;
  })();
}
"#;
        let out = decompile_source("home.tsx", input).unwrap().content;
        assert!(out.contains("<Show when={ready()}"));
    }

    #[test]
    fn scanner_advances_through_comments_in_non_jsx_iifes() {
        let input = r#"import { createElement as _$createElement } from "@opentui/solid";
export function Home() {
  const ignored = (() => {
    // This normal IIFE is not JSX and should not trap the scanner.
    return "plain";
  })();
  return (() => {
    var _el$ = _$createElement("box");
    return _el$;
  })();
}
"#;
        let out = decompile_source("home.tsx", input).unwrap().content;
        assert!(out.contains("<box />"));
        assert!(out.contains("const ignored = (() => {"));
    }
}
